#!/bin/sh
. scripts/functions_wbm.sh

log "this will run forever and can"
log "be stopped with 'killall ping'"
log "starting in 5 sec..."

sleep 5

cat $1 | while read -r line
do
    ip="$line"
    ping  $ip &
done
