#!/bin/sh

FILE="${1:-./routers}"
logger -s "using file '$FILE'"

LIST_FAILED=

while read -r LINE
do
	IP="$LINE"
	ping -c 1 $IP || LIST_FAILED="$LIST_FAILED $IP"
done <"$FILE"

for IP in $LIST_FAILED; do
	logger -s "failed IP: '$IP'"
done
