#!/bin/sh

FILE="$1"

while read -r LINE
do
    IP="$LINE"

    ssh -o StrictHostKeyChecking=no \
	-o UserKnownHostsFile=/dev/null \
	root@$IP 'ash -s'< scripts/stop_routing.sh
    echo "stopped routing on $IP"
done <"$FILE"
