#!/bin/sh

cat $1 | while read -r line
do
    ip="$line"
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$ip 'ash -s'< scripts/stop_routing.sh
    echo "stopped routing on $ip"
done
