#!/bin/bash

cat $1 | while read -r line
do
    ip="$line"
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$ip 'ash -s'< ../scripts/olsr2
    echo "olsrv2 launched on $ip"
    echo 'olsr2' >/tmp/MESHPROTO
done
