#!/bin/bash

cat $1 | while read -r line
do
    ip="$line"
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$ip 'ash -s'< ../scripts/batman-adv-4_no_airfair
    echo "batman launched on $ip"
    echo 'batman-adv-4' >/tmp/MESHPROTO
done
