#!/bin/bash

cat $1 | while read -r line
do
    ip="$line"
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$ip 'ash -s'< ../scripts/batman-adv
    echo "batman launched on $ip"
done
