#!/bin/bash

cat $1 | while read -r line
do
    ip="$line"
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$ip 'ash -s'< ../scripts/bmx7_tun_no_airfair
    echo "bmx7 launched on $ip"
    echo 'bmx7-tun' >/tmp/MESHPROTO
done
