#!/bin/bash

cat $1 | while read -r line
do
    ip="$line"
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$ip 'ash -s'< ../scripts/olsr1_no_airfair
    echo "olsrv1 launched on $ip"
    echo 'olsr1' >/tmp/MESHPROTO
done
