#!/bin/ash

#
# olsrd v2
#

killall -q olsrd2
sleep 1

ipv4=`ip -o addr show dev br-testbed|grep inet\ | awk '{print $4}' | sed -e s@/[0-9]*@/32@`
ipv6=`ip -o addr show dev br-testbed|grep inet6\ fc | awk '{print $4}' | sed -e s@/[0-9]*@/128@`

echo "loopback: ${ipv4} ${ipv6}"
ip addr add ${ipv4} dev lo
ip -6 addr add ${ipv6} dev lo
ip link set wlan1 up

olsrd2 --set interface[lo]. --set interface[wlan1]. --set lan_import[0].interface=br-testbed --set global.fork=true
